## **Libraries**

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## **Dataset Importing & Cleaning**

In [8]:
df= pd.read_csv(r"Synthetic.csv")
df.head()

   Unnamed: 0          X           Y
0           0  37.454012  126.746701
1           1  95.071431  293.927975
2           2  73.199394  225.441700
3           3  59.865848  183.586508
4           4  15.601864   39.020372

In [9]:
df=df.iloc[:,1:3]

In [11]:
df.head()

           X           Y
0  37.454012  126.746701
1  95.071431  293.927975
2  73.199394  225.441700
3  59.865848  183.586508
4  15.601864   39.020372

## **Extracting Features and labels**

In [12]:
x=df.iloc[:,0].values
y=df.iloc[:,1].values

In [13]:
x.shape,y.shape

((50,), (50,))

## **Gradient Descent**

In [ ]:
class GradientDescent:
    def __init__(self,x,y,lr=0.0001,epochs=10000,tolerance=0.001):
        self.x=x
        self.y=y
        self.lr=lr
        self.epochs=epochs
        self.tolerance=tolerance



    def initialize_parameters(self):
        w =np.array( np.random.randn()).reshape(1,1)
        b = np.zeros((1,1))
    def normalization(self):
        x = (x-np.mean(x))/np.std(x)
    def SGD(self):
        pass
    def BGD(self):
        pass
    def MBGD(self):
        pass
    def graph(self):
        pass

array([[-1.00416807]])

In [21]:
np.zeros((1,1))

array([[0.]])

In [23]:
x = (x-np.mean(x))/np.std(x)

In [ ]:
x.reshape(1,-1)

array([[-0.2496113 ,  1.76512621,  1.00031561,  0.53407475, -1.01372644,
        -1.01381079, -1.35618083,  1.46951733,  0.54266462,  0.91666857,
        -1.48730589,  1.83224825,  1.35155967, -0.8167878 , -0.92348815,
        -0.91796489, -0.49542545,  0.2756577 , -0.04888068, -0.54092903,
         0.58021232, -1.07150948, -0.53772773, -0.2782087 ,  0.03547831,
         1.18627988, -0.8610753 ,  0.23886491,  0.51224134, -1.39685922,
         0.56514817, -0.96300438, -1.33181553,  1.75873146,  1.81728978,
         1.26747928, -0.49412632, -1.2177497 ,  0.8333076 , -0.02018118,
        -1.13254745,  0.17222548, -1.43903665,  1.62038204, -0.65439565,
         0.75739054, -0.46930881,  0.25926349,  0.35242483, -0.91289479]])